# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 21ed3acc541a2cd4b0231cd9b274a9d46e02252ca4ea76ad1bbfe585c2ba94058a02f02e22a2dffae97806db617616b455b5d9c42aa0a5954da6df1ae0a92e47

test:
  secret_key_base: eef34806b41d379d6d2508c9e6fd8ec7eb5cb946599750210798135d20442870dc756632f76688f382be395120e843852e3d8ec91641b71d804041c670bdb527

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
